
exec : donnees_statiques.o utilitaires.o initialisation.o arrivee_des_patients.o patience_et_departs_forces.o affichage2.o actions.o deplacements.o sauvegarde.o scores.o menu_principal.o boucle_principale.o main.o 
  gcc *.o -o exec

donnees_statiques.o : donnees_statiques.c structures_projet_dentiste.h
    gcc -c donnees_statiques.c

utilitaires.o : utilitaires.c structures_projet_dentiste.h
    gcc -c utilitaires.c

initialisation.o : initialisation.c structures_projet_dentiste.h
    gcc -c initialisation.c

arrivee_des_patients.o : arrivee_des_patients.c structures_projet_dentiste.h
    gcc -c arrivee_des_patients.c

patience_et_departs_forces.o : patience_et_departs_forces.c structures_projet_dentiste.h
    gcc -c  patience_et_departs_forces.c

affichage2.o : affichage2.c structures_projet_dentiste.h
    gcc -c affichage2.c

actions.o : actions.c structures_projet_dentiste.h
    gcc -c actions.c

deplacements.o : deplacements.c structures_projet_dentiste.h
    gcc -c deplacements.c

sauvegarde.o : sauvegarde.c structures_projet_dentiste.h
    gcc -c sauvegarde.c

scores.o : scores.c structures_projet_dentiste.h
    gcc -c scores.c

menu_principal.o : menu_principal.c structures_projet_dentiste.h
    gcc -c menu_principal.c

boucle_principale.o : boucle_principale.c structures_projet_dentiste.h
    gcc -c boucle_principale.c

main.o : main.c structures_projet_dentiste.h
    gcc -c main.c
